name: Deploy to Server

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        if [[ $GITHUB_REF == refs/heads/dev ]]; then
          ssh -o StrictHostKeyChecking=no -p "$PORT" "$USER@$HOST" << 'EOF'
            cd ~/apps/dev || exit
            git pull origin dev || exit
            npm install --production || exit
            npm run build || exit
            pm2 restart dev-app || pm2 start npm --name dev-app -- start || exit
          EOF
        fi
        
        if [[ $GITHUB_REF == refs/heads/main ]]; then
          ssh -o StrictHostKeyChecking=no -p "$PORT" "$USER@$HOST" << 'EOF'
            cd ~/apps/prod || exit
            git pull origin main || exit
            npm install --production || exit
            npm run build || exit
            pm2 restart prod-app || pm2 start npm --name prod-app -- start || exit
          EOF
        fi
