name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 185.19.201.131 >> ~/.ssh/known_hosts

    - name: Deploy to Dev
      run: |
        ssh root@192.168.100.111 << 'EOF'
        cd /var/www/dev || git clone https://github.com/alirasouliwebdeveloper/Portfolio.git /var/www/dev
        cd /var/www/dev
        git reset --hard
        git pull origin main
        npm install
        npm run build
        pm2 restart dev || pm2 start npm --name "dev" -- start
        pm2 save
        EOF
