name: Deploy to Server

on:
  push:
    branches:
      - main
      - feature/develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 185.19.201.131 >> ~/.ssh/known_hosts
          echo "GITHUB_REF: $GITHUB_REF"

      - name: Deploy main or develop
        run: |
          ssh -i ~/.ssh/id_rsa root@185.19.201.131 << 'EOF'
            if [ "$GITHUB_REF" = "refs/heads/main" ]; then
              BRANCH="main"
              DIR="/var/www/main"
            elif [ "$GITHUB_REF" = "refs/heads/feature/develop" ]; then
              BRANCH="feature/develop"
              DIR="/var/www/develop"
            else
              echo "Unsupported branch: $GITHUB_REF"
              exit 1
            fi

            if [ ! -d "$DIR" ]; then
              mkdir -p "$DIR"
              cd "$DIR"
              git init
              git remote add origin git@github.com:alirasouliwebdeveloper/Portfolio.git
              git fetch origin $BRANCH
              git checkout $BRANCH
            else
              cd "$DIR"
            fi
            git pull origin $BRANCH
            npm install
            npm run build
            pm2 reload ecosystem.config.js --only $BRANCH || pm2 start ecosystem.config.js --only $BRANCH
            pm2 save
          EOF
