name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Install Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Install dependencies and build
    - name: Install dependencies
      run: |
        npm install
        npm run build

    # 4. Deploy to Server
    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        PORT: ${{ secrets.SERVER_PORT }}
        PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      run: |
        if [[ $GITHUB_REF == refs/heads/dev ]]; then
          ssh -i "$PRIVATE_KEY" -p "$PORT" "$USER@$HOST" << 'EOF'
          cd ~/apps/dev
          git pull origin dev
          npm install --production
          npm run build
          pm2 restart dev-app || pm2 start npm --name dev-app -- start
          EOF
        fi

        if [[ $GITHUB_REF == refs/heads/main ]]; then
          ssh -i "$PRIVATE_KEY" -p "$PORT" "$USER@$HOST" << 'EOF'
          cd ~/apps/prod
          git pull origin main
          npm install --production
          npm run build
          pm2 restart prod-app || pm2 start npm --name prod-app -- start
          EOF
        fi
