name: Deploy to Server

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Deploy to server (dev environment)
      if: github.ref == 'refs/heads/dev'
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} "
          cd ~/apps/dev || mkdir -p ~/apps/dev
          git pull origin dev
          npm install --production
          npm run build
          pm2 restart dev-app || pm2 start npm --name dev-app -- start
        "

    - name: Deploy to server (prod environment)
      if: github.ref == 'refs/heads/main'
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOST }} "
          cd ~/apps/prod || mkdir -p ~/apps/prod
          git pull origin main
          npm install --production
          npm run build
          pm2 restart prod-app || pm2 start npm --name prod-app -- start
        "
