name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 185.19.201.131 >> ~/.ssh/known_hosts

    - name: Create text file on server
      run: |
        ssh root@185.19.201.131 "echo 'GitHub Actions is working!' > /root/testfile.txt"
