name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 185.19.201.131 >> ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        ssh root@185.19.201.131 << 'EOF'
        pm2 stop all || true
        rm -rf /var/www/Portfolio
        git clone https://github.com/alirasouliwebdeveloper/Portfolio.git /var/www/Portfolio
        cd /var/www/Portfolio
        npm install
        pm2 start /var/www/Portfolio/ecosystem.config.js
        pm2 save
        EOF
