name: Deploy Application

on:
  push:
    branches:
      - main
      - feature/develop

jobs:
  setup_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 185.19.201.131 >> ~/.ssh/known_hosts

      - name: Export GITHUB_REF as output
        id: set_ref
        run: echo "::set-output name=branch_ref::${GITHUB_REF}"

  deploy:
    needs: setup_ssh
    runs-on: ubuntu-latest
    steps:
      - name: Access GITHUB_REF from setup_ssh
        run: echo GITHUB_REF:$needs.setup_ssh.outputs.branch_ref

      - name: Clone or Pull Repository
        run: |
          BRANCH_NAME=${{ needs.setup_ssh.outputs.branch_ref#refs/heads/ }}
          echo "Current branch: $BRANCH_NAME"
          if [ "$BRANCH_NAME" == "main" ]; then
            DEST_DIR="/var/www/main"
          else
            DEST_DIR="/var/www/develop"
          fi

          if [ ! -d "$DEST_DIR/.git" ]; then
            git clone -b $BRANCH_NAME git@github.com:alirasouliwebdeveloper/Portfolio.git $DEST_DIR
          else
            cd $DEST_DIR
            git reset --hard
            git pull origin $BRANCH_NAME
          fi
